# Badania

Jedna z metod badań społecznych, w której do zbierania informacji od respondentów wykorzystuje się wystandaryzowany kwestionariusz. \cite{French2010a}

Dla ustalenia badanej populacji konsumentów \cite{nbp2012} stosuje się dobór losowy, gdy niewielka jest ich liczba i nieznana ich struktura, dobór losowy systematyczny \cite{nbp2012}, gdy dostępna jest lista całej populacji oraz dobór losowy \cite{systems2001} warstwowy dla uzyskania bardziej dokładnych wyników charakteryzujących badanych. \cite{Shotton2000, French2010, Shotton2010, Shotton1989, French2010a, Shotton1999}

Stan negatywnych emocji i frustracji w niektórych kręgach akademickiej makroekonomii \textcite[25]{krugman2009} najlepiej oddaje skrajna wypowiedź Krugmana \parencite*{krugman2009}: „Większość z tego, co stworzono w ramach makroekonomii w ciągu ostatnich 30 lat okazało się w najlepszym razie bezużyteczne lub w najgorszym razie szkodliwe" \citepage[20]{krugman2009}.

Wyniki badań przedstawiono w @tbl-wyniki. Jak widać z danych zawartych w tabeli, wartości parametrów $\alpha$, $\beta$ i $\gamma$ zostały zestawione z odpowiadającymi im wynikami liczbowymi. Równanie @eq-przyklad z poprzedniego rozdziału ilustruje podstawowe operacje matematyczne możliwe do zastosowania w pracy.

\begin{table}[h!]
\centering
\caption{Wyniki badań}\label{tbl-wyniki}
\begin{tabular}{l|c|r}
\textbf{Value 1} & \textbf{Value 2} & \textbf{Value 3}\\
$\alpha$ & $\beta$ & $\gamma$ \\
\hline
1 & 1110.1 & a\\
2 & 10.1 & b\\
3 & 23.113231 & c\\
\end{tabular}
\par\vspace{0.3em}
{\footnotesize Źródło: \cite{Shotton1999}}
\end{table}

## Analiza wyników

Na podstawie wyników z @tbl-wyniki można stwierdzić, że wartości rosną monotonicznie. Poniższe równanie (@eq-regresja) opisuje prostą regresję liniową, która mogłaby zostać zastosowana do analizy tych danych:

$$
y = \beta_0 + \beta_1 x + \varepsilon
$$ {#eq-regresja}

Jak wspomniano w rozdziale @sec-r-example, system Quarto pozwala na integrację kodu R bezpośrednio w tekście pracy. Wyniki z @eq-regresja można obliczyć za pomocą poniższego kodu:

```{r}
#| label: tbl-regresja
#| tbl-cap: "Wyniki regresji liniowej"
#| echo: true
dane <- data.frame(
  x = c(1, 2, 3),
  y = c(1110.1, 10.1, 23.113231)
)
model <- lm(y ~ x, data = dane)
knitr::kable(
  summary(model)$coefficients,
  digits = 3
)
```

Wyniki regresji z @tbl-regresja wskazują na kierunek zależności między zmiennymi.
